version: "3.9"
services:
  hadikontroller:
    build:
      dockerfile: Dockerfile
    devices:
      - "/dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0-port0:/dev/ttyscd30"
    environment:
      MINITSDB_IP: "192.168.2.91"
      MINITSDB_PORT: "8001"
